# necessary until containers support postgres 9.5
sudo: required
dist: trusty

language: python

install: pip3 install -q -r dev-requirements.txt

matrix:
  include:
    - python: 3.6.0
      addons:
        postgresql: 9.5
      env: PG=9.5
    - python: 3.6.0
      addons:
        postgresql: 9.4
      env: PG=9.4
    - python: 3.6.0
      addons:
        postgresql: 9.3
      env: PG=9.3
    - python: 3.5.2
      addons:
        postgresql: 9.5
      env: PG=9.5
    - python: 3.5.2
      addons:
        postgresql: 9.4
      env: PG=9.4
    - python: 3.5.2
      addons:
        postgresql: 9.3
      env: PG=9.3
    - python: 3.5.0
      addons:
        postgresql: 9.5
      env: PG=9.5
    - python: 3.4
      addons:
        postgresql: 9.5
      env: PG=9.5

script: tox

after_script: coveralls
