# necessary until containers support postgres 9.5
sudo: required
dist: trusty

language: python

install: pip3 install -q -U -r dev-requirements.txt

matrix:
  include:
    - python: 3.6
      addons:
        postgresql: 9.5
      env: PG=9.5
    - python: 3.6
      addons:
        postgresql: 9.4
      env: PG=9.4
    - python: 3.6
      addons:
        postgresql: 9.3
      env: PG=9.3

script: tox

after_script: coveralls
