version: 2

jobs:
  build:
    working_directory: .
    docker:
      - image: themattrix/tox
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip3 install -q -r dev-requirements.txt
      - run:
          name: Test all versions
          command: tox -- --junitxml={$CIRCLE_TEST_REPORTS}/temporal-sqlalchemy/junit.xml
